Repository foldfelis-QO/SqState.jl, pull requests merged in 2021-02, with the labels that each got.

#8 Fix the god damn bug of the index bases of number state
  Project.toml
  src/SqState.jl
  src/polynomial.jl
  src/render.jl
  src/utils.jl
  test/plot.jl
  test/polynomial.jl
  test/render.jl
  test/runtests.jl
  test/utils.jl
Labels: bug, enhancement, refactor

#7 Add setter and create_wigner
  src/wigner.jl
  test/wigner.jl
Labels: enhancement, refactor

#9 test save
  src/render.jl
  test/render.jl
Labels: enhancement

#10 Refactor
  src/SqState.jl
  src/plot.jl
  src/render.jl
  src/wigner.jl
  test/main.jl
  test/plot.jl
  test/render.jl
  test/runtests.jl
  test/wigner.jl
Labels: refactor

#11 Add plot notebook
  Project.toml
  notebook/plot_wigner.jl
Labels: documentation, enhancement

#12 remove reshape cell and implement surface plot
  .github/workflows/ci.yml
  Project.toml
  notebook/plot_wigner.jl
  src/plot.jl
  test/main.jl
  test/plot.jl
Labels: bug, enhancement, refactor

#13 plot surface with gr
  Project.toml
  src/plot.jl
  test/main.jl
Labels: refactor
